### ISSUE TITLE
puppetlabs-stdlib dependency not declared

### ISSUE THREAD

**Issue by brownmike** [gildas/puppet-homebrew#14]
I tried to use this module recently on a fresh install and it fails when a call to the `emtpy` function in the standard lib is made. The issue is resolved after running `puppet module install puppetlabs-stdlib`. This dependency should be declared in the module

**Comment by gildas** [comment]
Thanks a lot for your pull request, I just merged it.

I guess I missed this one as I always have stdlib loaded. Thanks a lot again!
